name: Daily LinkedIn to HubSpot Sync

on:
  schedule:
    # Run once daily at a random time between 9 AM and 5 PM UTC on weekdays
    - cron: '0 9 * * 1-5'  # This will run at 9 AM UTC, and we'll use a random delay
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create necessary directories
      run: |
        mkdir -p data
        mkdir -p scripts/logs
        touch data/post_scrapes.db  # Create empty db if it doesn't exist

    - name: Random delay
      run: |
        # Generate random delay between 0 and 8 hours (9 AM to 5 PM)
        DELAY=$((RANDOM % 28800))
        echo "Sleeping for $DELAY seconds..."
        sleep $DELAY

    - name: Download database
      uses: actions/download-artifact@v4
      with:
        name: post_scrapes.db
        path: data/
      continue-on-error: true  # Continue if no previous artifact exists
        
    - name: Pull posts from Google Sheets
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        cd scripts
        echo "Starting Google Sheets sync..."
        python gs_sql.py
        echo "Google Sheets sync completed"
        
    - name: Scrape LinkedIn posts
      env:
        APIFY_API_KEY: ${{ secrets.APIFY_API_KEY }}
      run: |
        cd scripts
        echo "Starting LinkedIn scraping..."
        python scrape.py
        echo "LinkedIn scraping completed"
        
    - name: Sync with HubSpot
      env:
        APIFY_API_KEY: ${{ secrets.APIFY_API_KEY }}
        HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
      run: |
        cd scripts
        echo "Starting HubSpot sync..."
        python sql_hs.py
        echo "HubSpot sync completed"

    - name: Upload database
      uses: actions/upload-artifact@v4
      with:
        name: post_scrapes.db
        path: data/post_scrapes.db
        retention-days: 90  # Keep the artifact for 90 days